# -*- coding: utf-8 -*-
"""AI_ASSISTED-LAB-6.3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nrLaxed6uOCn0dNFtkmKLJS3MKqMb7AL

@Author: HIMESH

Task-1
"""

class Student:
    def __init__(self, name, roll_no, marks):
        self.name = name
        self.roll_no = roll_no
        self.marks = marks

    def is_pass(self):
        return self.marks >= 40

# Create some student objects
student1 = Student("Alice", "S001", 45)
student2 = Student("Bob", "S002", 38)
student3 = Student("Charlie", "S003", 70)

# Test the is_pass() method
print(f"{student1.name} (Roll No: {student1.roll_no}) with marks {student1.marks} passed: {student1.is_pass()}")
print(f"{student2.name} (Roll No: {student2.roll_no}) with marks {student2.marks} passed: {student2.is_pass()}")
print(f"{student3.name} (Roll No: {student3.roll_no}) with marks {student3.marks} passed: {student3.is_pass()}")

"""TASK-2

### Right-Angled Triangle Star Pattern using a `for` loop
"""

def print_right_angle_triangle_for(rows):
    for i in range(1, rows + 1):
        print('*' * i)

print("Pattern using for loop:")
print_right_angle_triangle_for(5)

"""### Right-Angled Triangle Star Pattern using a `while` loop"""

def print_right_angle_triangle_while(rows):
    i = 1
    while i <= rows:
        print('*' * i)
        i += 1

print("\nPattern using while loop:")
print_right_angle_triangle_while(5)

"""TASK-3"""

def check_number_sign(number):
    if number > 0:
        print(f"{number} is a positive number.")
    elif number < 0:
        print(f"{number} is a negative number.")
    else:
        print(f"{number} is zero.")

# Test the function with multiple inputs
print("Testing check_number_sign function:")
check_number_sign(10)
check_number_sign(-5)
check_number_sign(0)
check_number_sign(100.5)
check_number_sign(-0.001)

"""TASK-4"""



def check_discount(age, is_member):
    print(f"Checking discount for age {age}, member status: {is_member}")
    if age >= 60:
        print("  Eligible for Senior discount.")
        if is_member:
            print("  Eligible for Additional member discount.")
        else:
            print("  Not eligible for additional member discount.")
    else:
        print("  Not eligible for Senior discount.")
        if is_member:
            print("  Eligible for Member discount.")
        else:
            print("  No discount eligibility based on age or membership.")

# Test the function with multiple inputs
print("\n--- Testing check_discount function ---")
check_discount(65, True) # Senior and member
check_discount(62, False) # Senior only
check_discount(30, True) # Member only
check_discount(25, False) # No discount
check_discount(60, True) # Edge case: exactly 60 and member
check_discount(59, True) # Edge case: just under 60 and member

"""TASK-5"""

import math

class Circle:
    def __init__(self, radius):
        if radius < 0:
            raise ValueError("Radius cannot be negative")
        self.radius = radius

    def area(self):
        return math.pi * (self.radius ** 2)

    def circumference(self):
        return 2 * math.pi * self.radius